XPATH_PRICE_LTH = "//div[text()='Price -- Low to High']"
XPATH_ITEMS_CARD = "(//div[@class='_1xHGtK _373qXS'])[3]/a"
XPATH_LABEL = "//select[@class='_2YxCDZ']"
XPATH_LABEL_MIN = "(//select[@class='_2YxCDZ'])[1]"
XPATH_LABEL_MAX = "(//select[@class='_2YxCDZ'])[2]"
